const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const content=$('#appContent');
const modalBackdrop=$('#filmModalBackdrop');
const modal=$('#filmModal');
const sheetBackdrop=$('#sheetBackdrop');
const sheet=$('#sheet');
const searchPanel=$('#searchPanel');
const searchInput=$('#globalSearch');
let currentView='profile';
let searchTimer=null;
let needsRefresh=false;
let cachedProfile=null;
const CLOUD_API='https://yfmxoimttdblbejaxwry.supabase.co/functions/v1/kinoala-cloud-api';
const CLOUD_KEY='sb_publishable_sDyahW4aobFkweiiG1jrmw_36_QtfDb';
let ownerSession=localStorage.getItem('kinoala_owner_session')||'';
let isOwner=false;
let activeProfileTab=localStorage.getItem('kinoala_profile_tab')==='tv'?'tv':'films';

async function api(path,options={}){
  const controller=options.signal?null:new AbortController();
  const timer=controller?setTimeout(()=>controller.abort(),30000):null;
  const method=String(options.method||'GET').toUpperCase();
  let body={};if(options.body){try{body=typeof options.body==='string'?JSON.parse(options.body):options.body}catch{body={}}}
  try{
    const response=await fetch(CLOUD_API,{method:'POST',headers:{'Content-Type':'application/json','apikey':CLOUD_KEY,...(ownerSession?{'x-kinoala-session':ownerSession}:{}),...(options.headers||{})},body:JSON.stringify({path,method,body}),signal:options.signal||controller?.signal});
    const data=await response.json().catch(()=>({}));
    if(response.status===401&&ownerSession){ownerSession='';localStorage.removeItem('kinoala_owner_session');isOwner=false;syncOwnerUi?.()}
    if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);
    return data;
  }catch(err){if(err?.name==='AbortError')throw new Error('Kinoala took too long to respond. Please try again.');throw err}
  finally{if(timer)clearTimeout(timer)}
}
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function reviewHtml(v=''){
  const raw=String(v??'');
  if(!raw.trim())return '<p class="review-empty">No written review.</p>';
  // <caption> is not valid as a free-standing HTML element, so normalize it to a
  // private element before DOMParser and render it back as a styled caption.
  const normalized=raw
    .replace(/<\s*caption\s*>/gi,'<kino-caption>')
    .replace(/<\s*\/\s*caption\s*>/gi,'</kino-caption>');
  const parsed=new DOMParser().parseFromString(`<div id="reviewSource">${normalized}</div>`,'text/html');
  const source=parsed.querySelector('#reviewSource');
  const out=document.createElement('div');
  const allowed=new Set(['B','STRONG','I','EM','BR','BLOCKQUOTE','P','A','H1','H2','H3','KINO-CAPTION']);
  const clean=node=>{
    if(node.nodeType===Node.TEXT_NODE){
      const frag=document.createDocumentFragment();String(node.nodeValue||'').split('\n').forEach((part,i,arr)=>{frag.append(document.createTextNode(part));if(i<arr.length-1)frag.append(document.createElement('br'))});return frag;
    }
    if(node.nodeType!==Node.ELEMENT_NODE)return document.createDocumentFragment();
    if(!allowed.has(node.tagName)){const frag=document.createDocumentFragment();[...node.childNodes].forEach(c=>frag.append(clean(c)));return frag}
    if(node.tagName==='KINO-CAPTION'){
      const el=document.createElement('div');el.className='review-caption';[...node.childNodes].forEach(c=>el.append(clean(c)));return el;
    }
    const tag=node.tagName==='B'?'strong':node.tagName==='I'?'em':node.tagName.toLowerCase();const el=document.createElement(tag);
    if(tag==='a'){const href=node.getAttribute('href')||'';if(/^https?:\/\//i.test(href)){el.href=href;el.target='_blank';el.rel='noopener noreferrer'}else{const frag=document.createDocumentFragment();[...node.childNodes].forEach(c=>frag.append(clean(c)));return frag}}
    [...node.childNodes].forEach(c=>el.append(clean(c)));return el;
  };
  [...source.childNodes].forEach(n=>out.append(clean(n)));
  if(!out.querySelector('p,blockquote,h1,h2,h3,.review-caption')){const p=document.createElement('p');while(out.firstChild)p.append(out.firstChild);out.append(p)}
  return out.innerHTML;
}
function today(){return new Date().toISOString().slice(0,10)}
function fmtDate(v){if(!v)return '—';const raw=String(v).slice(0,10);const d=new Date(`${raw}T12:00:00`);return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function shortDate(v){if(!v)return '';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short'}).format(d)}
function ratingText(v){return v==null?'':Number(v).toFixed(Number(v)%1?1:0)}
function tagChips(tags){if(!tags)return '';const items=String(tags).split(',').map(x=>x.trim()).filter(Boolean);return items.length?`<div class="tag-row">${items.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}
function reviewImagesHtml(entry,{compact=false}={}){
  const images=(entry?.review_images||[]).filter(Boolean);
  if(!images.length)return '';
  const shown=compact?images.slice(0,3):images;
  return `<div class="review-image-gallery ${compact?'compact':''}">${shown.map((src,i)=>`<figure><img loading="lazy" src="${esc(src)}" alt="Review image ${i+1}"></figure>`).join('')}${compact&&images.length>3?`<span class="review-image-more">+${images.length-3}</span>`:''}</div>`;
}
function reviewImageEditor(existing=null){
  const paths=existing?.review_image_paths||[];
  const urls=existing?.review_images||[];
  return `<div class="field full review-images-field"><label>Review images <span>optional · up to 8</span></label><div class="review-image-editor-grid" id="reviewImageExisting">${paths.map((path,i)=>`<div class="review-image-edit-item" data-review-image-path="${esc(path)}"><img src="${esc(urls[i]||'')}" alt=""><button type="button" aria-label="Remove image">×</button></div>`).join('')}</div><div class="review-image-editor-grid" id="reviewImageNewPreview"></div><input class="form-control" id="reviewImageInput" type="file" name="review_images" accept="image/png,image/jpeg,image/webp" multiple><small class="format-hint">Images appear beneath the written review. PNG, JPEG or WebP, up to 5 MB each.</small></div>`;
}
function bindReviewFormatting(textarea){
  if(!textarea)return;
  const formats={h1:['<h1>','</h1>','Heading'],h2:['<h2>','</h2>','Heading'],h3:['<h3>','</h3>','Heading'],b:['<b>','</b>','bold text'],i:['<i>','</i>','italic text'],quote:['<blockquote>','</blockquote>','Quote'],caption:['<caption>','</caption>','Caption']};
  $$('[data-review-format]',sheet).forEach(btn=>btn.onclick=()=>{
    const cfg=formats[btn.dataset.reviewFormat];if(!cfg)return;
    const start=textarea.selectionStart??textarea.value.length,end=textarea.selectionEnd??start;
    const selected=textarea.value.slice(start,end)||cfg[2];
    const replacement=`${cfg[0]}${selected}${cfg[1]}`;
    textarea.setRangeText(replacement,start,end,'select');textarea.focus();
  });
}
function reviewFormatToolbar(){
  return `<div class="review-format-toolbar" aria-label="Review formatting"><button type="button" data-review-format="h1">H1</button><button type="button" data-review-format="h2">H2</button><button type="button" data-review-format="h3">H3</button><span></span><button type="button" data-review-format="b"><b>B</b></button><button type="button" data-review-format="i"><i>I</i></button><button type="button" data-review-format="quote">❝</button><button type="button" data-review-format="caption">Caption</button></div>`;
}
function starIcons(value,size='normal'){
  const n=Number(value||0);
  return `<span class="stars-display ${size}" aria-label="${n||0} out of 5 stars">${[1,2,3,4,5].map(i=>{const fill=Math.max(0,Math.min(100,(n-(i-1))*100));return `<span class="star-shell"><span class="star-empty">★</span><span class="star-filled" style="width:${fill}%">★</span></span>`}).join('')}</span>`;
}
function ratingPicker(value,id,{clear=true}={}){
  const n=value==null?0:Number(value);
  return `<div class="rating-picker" id="${id}" data-value="${n}">${[1,2,3,4,5].map(i=>`<button type="button" class="rating-star-btn" data-star="${i}" aria-label="Rate ${i} stars"><span class="star-shell"><span class="star-empty">★</span><span class="star-filled">★</span></span></button>`).join('')}${clear?'<button type="button" class="rating-clear">clear</button>':''}</div>`;
}
function paintRatingPicker(root,value){if(!root)return;const n=Number(value||0);root.dataset.value=String(n);$$('.rating-star-btn',root).forEach(btn=>{const i=Number(btn.dataset.star);const fill=Math.max(0,Math.min(100,(n-(i-1))*100));$('.star-filled',btn).style.width=`${fill}%`})}
function bindRatingPicker(id,initial,onChange){
  const root=$(`#${id}`);if(!root)return;let saved=Number(initial||0);paintRatingPicker(root,saved);
  $$('.rating-star-btn',root).forEach(btn=>{
    btn.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=btn.getBoundingClientRect();const i=Number(btn.dataset.star);paintRatingPicker(root,i-(e.clientX-r.left<r.width/2?.5:0))});
    btn.addEventListener('click',async e=>{const r=btn.getBoundingClientRect();const i=Number(btn.dataset.star);saved=i-(e.clientX-r.left<r.width/2?.5:0);paintRatingPicker(root,saved);await onChange?.(saved)});
  });
  root.addEventListener('mouseleave',()=>paintRatingPicker(root,saved));
  $('.rating-clear',root)?.addEventListener('click',async()=>{saved=0;paintRatingPicker(root,0);await onChange?.(null)});
}
function typeLabel(m){return (m.media_type||'movie')==='tv'?'TV SERIES':'FILM'}
function posterHtml(m){return m.poster_url?`<img loading="lazy" src="${esc(m.poster_url)}" alt="${esc(m.title)} poster">`:`<div class="poster-placeholder"><span>${esc(m.title)}</span></div>`}
function filmCard(m,{compact=false,showTitle=true}={}){
  return `<article class="film-card ${compact?'compact':''}" data-film-id="${m.id}">
    <div class="poster">${posterHtml(m)}${m.media_type==='tv'?'<span class="media-pill">TV</span>':''}${m.liked?'<span class="poster-heart">♥</span>':''}</div>
    ${showTitle?`<div class="film-card-title" title="${esc(m.title)}">${esc(m.title)}</div><div class="film-card-meta"><span>${m.year||'—'}</span>${m.rating!=null?starIcons(m.rating,'tiny'):''}</div>`:''}
  </article>`;
}
function sectionRow(title,subtitle,items,view){if(!items?.length)return '';return `<section class="section"><div class="section-head"><div><h2>${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${view?`<button data-view="${view}">View all →</button>`:''}</div><div class="poster-row">${items.map(x=>filmCard(x,{compact:true})).join('')}</div></section>`}
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toasts').append(el);setTimeout(()=>el.remove(),3200)}
function loading(){content.innerHTML='<div class="loading-state"><div class="spinner"></div><p>Loading…</p></div>'}
function setActive(view){$$('.nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function bindFilmCards(root=document){$$('[data-film-id]',root).forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('button,[data-log-type],[data-list-id]'))return;openMedia(Number(el.dataset.filmId))}))}
function bindViewLinks(root=document){$$('[data-view]',root).forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)))}
function bindLogLinks(root=document){$$('[data-log-type][data-log-id]',root).forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openLogDetail(el.dataset.logType,Number(el.dataset.logId))}))}
function avatarMarkup(url,username,className='avatar'){const initial=esc((username||'K')[0]?.toUpperCase()||'K');return `<span class="${className}" data-avatar-fallback="${initial}">${url?`<img src="${esc(url)}" alt="" onerror="this.remove();this.parentElement.classList.add('avatar-fallback')">`:initial}</span>`}
function setMiniProfile(p={}){const target=$('#miniProfile');if(!target)return;const username=p.username||'kinoala';target.innerHTML=`${avatarMarkup(p.avatar_url,username)}<span class="mini-profile-copy"><strong>${esc(username)}</strong><small>${esc(p.location||'local profile')}</small></span>`}
function openSheet(html){sheet.innerHTML=html;sheetBackdrop.classList.remove('hidden');$('.sheet-close',sheet)?.addEventListener('click',closeSheet)}
function closeSheet(){sheetBackdrop.classList.add('hidden');sheet.innerHTML=''}
function closeModal(){modalBackdrop.classList.add('hidden');modal.innerHTML='';if(needsRefresh){needsRefresh=false;navigate(currentView)}}
function markRefresh(){needsRefresh=true}

async function navigate(view){
  currentView=view;setActive(view);loading();searchPanel.classList.add('hidden');closeSheet();
  try{
    if(view==='profile')await renderProfile();
    else if(view==='films')await renderFilms();
    else if(view==='lists')await renderLists();
    else if(view==='watchlist')await renderWatchlist();
    else if(view==='activity')await renderActivity();
    else if(view==='settings')await renderSettings();
  }catch(e){content.innerHTML=`<div class="empty"><h3>Something went wrong</h3><p>${esc(e.message)}</p></div>`}
}

function ratingsHistogram(distribution,total,{compact=false}={}){
  const buckets=[.5,1,1.5,2,2.5,3,3.5,4,4.5,5];const counts=buckets.map(r=>Number(distribution.find(x=>Number(x.rating)===r)?.count||0));const max=Math.max(...counts,1);
  return `<section class="ratings-histogram ${compact?'compact':''}"><div class="ratings-title"><span>RATINGS</span><b>${total||counts.reduce((a,b)=>a+b,0)}</b></div><div class="rating-rule"></div><div class="histogram-body"><div class="histogram-edge one">★</div><div class="histogram-bars">${counts.map((c,i)=>`<div class="histogram-column" title="${buckets[i]} stars · ${c}"><i style="height:${c?Math.max(3,c/max*100):2}%"></i></div>`).join('')}</div><div class="histogram-edge five">★★★★★</div></div></section>`
}
function logSubtitle(x){if(x.log_type==='season')return `Season ${x.season_number}`;if(x.log_type==='episode')return `S${String(x.season_number||0).padStart(2,'0')}E${String(x.episode_number||0).padStart(2,'0')} · ${x.episode_name||'Episode'}`;if(x.log_type==='review'&&x.media_type==='tv')return 'Series review';return x.rewatch?'Rewatch':'Film'}
function compactLog(x){return `<button class="compact-log" data-log-type="${x.log_type}" data-log-id="${x.log_id}"><div class="compact-log-poster">${x.poster_url?`<img src="${esc(x.poster_url)}" alt="">`:''}</div><div class="compact-log-copy"><strong>${esc(x.title)} <span>${x.year||''}</span></strong><small>${esc(logSubtitle(x))} · ${fmtDate(x.watched_date)}</small>${x.rating!=null?starIcons(x.rating,'tiny'):''}${x.review?`<p>${esc(String(x.review).replace(/<[^>]+>/g,'').slice(0,150))}</p>`:''}</div>${x.liked?'<i class="log-like">♥</i>':''}</button>`}

function topFiveCard(m,index){
  if(!m)return `<button class="top5-empty" data-empty-top5="${index}"><span>＋</span><b>Add film</b></button>`;
  const bg=m.backdrop_url?`style="background-image:linear-gradient(180deg,rgba(9,13,16,.08) 0%,rgba(9,13,16,.38) 36%,rgba(12,16,19,.98) 100%),url('${esc(m.backdrop_url)}')"`:'';
  return `<article class="top5-card" data-film-id="${m.id}" ${bg}><div class="top5-rank">0${index+1}</div><div class="top5-content"><div class="top5-poster">${posterHtml(m)}</div><div class="top5-copy"><h3>${esc(m.title)}</h3><span>${m.year||''}</span>${m.rating!=null?starIcons(m.rating,'small'):''}</div></div></article>`;
}
function profileDiary(logs,total){
  const rows=(logs||[]).slice(0,9);
  if(!rows.length)return `<section class="profile-side-block"><div class="profile-block-head"><span>DIARY</span><b>${total||0}</b></div><div class="profile-rule"></div><div class="empty compact">No diary entries yet.</div></section>`;
  const groups=[];for(const x of rows){const d=new Date(`${String(x.watched_date).slice(0,10)}T12:00:00`);const key=`${d.getFullYear()}-${d.getMonth()}`;let g=groups.at(-1);if(!g||g.key!==key){g={key,month:d.toLocaleString('en-AU',{month:'short'}).toUpperCase(),items:[]};groups.push(g)}g.items.push(x)}
  return `<section class="profile-side-block"><div class="profile-block-head"><span>DIARY</span><b>${total||rows.length}</b></div><div class="profile-rule"></div><div class="profile-diary">${groups.map(g=>`<div class="diary-month"><div class="diary-month-badge">${g.month}</div><div class="diary-month-items">${g.items.map(x=>`<button data-log-type="${x.log_type}" data-log-id="${x.log_id}"><time>${new Date(`${String(x.watched_date).slice(0,10)}T12:00:00`).getDate()}</time><span>${esc(x.title)}</span></button>`).join('')}</div></div>`).join('')}</div></section>`;
}
function profileActivity(actions,username){
  const rows=(actions||[]).slice(0,6);if(!rows.length)return '';
  const describe=a=>{if(a.action==='logged')return `watched <strong>${esc(a.title||'a film')}</strong>`;if(a.action==='rated')return `rated <strong>${esc(a.title||'a title')}</strong> ${a.rating!=null?starIcons(a.rating,'tiny'):''}`;if(a.action==='liked')return `liked <strong>${esc(a.title||'a title')}</strong>`;if(a.action==='reviewed')return `reviewed <strong>${esc(a.title||'a title')}</strong>`;if(a.action==='created_list')return `created <strong>${esc(a.list_name||a.details||'a list')}</strong>`;if(a.action==='added_to_list')return `added <strong>${esc(a.title||'a title')}</strong> to ${esc(a.list_name||'a list')}`;if(a.action==='logged_season')return `logged Season ${a.season_number||''} of <strong>${esc(a.title||'a show')}</strong>`;if(a.action==='logged_episode')return `logged an episode of <strong>${esc(a.title||'a show')}</strong>`;return `updated <strong>${esc(a.title||a.list_name||'the library')}</strong>`};
  return `<section class="profile-side-block profile-activity-block"><div class="profile-block-head"><span>ACTIVITY</span><button data-view="activity">ALL</button></div><div class="profile-rule"></div><div class="profile-activity-timeline">${rows.map(a=>`<div class="profile-activity-item"><i></i><p><b>${esc(username)}</b> ${describe(a)} <time>${fmtDate(a.created_at)}</time></p></div>`).join('')}</div></section>`;
}
function recentReviewItem(x){
  const context=x.log_type==='season'?`<span class="review-context">Season ${x.season_number}</span>`:(x.log_type==='review'&&x.media_type==='tv'?'<span class="review-context">Series review</span>':'');
  return `<button class="profile-review-row" data-log-type="${x.log_type}" data-log-id="${x.log_id}"><div class="profile-review-poster">${x.poster_url?`<img src="${esc(x.poster_url)}" alt="">`:''}</div><div class="profile-review-copy"><div class="profile-review-title"><h3>${esc(x.title)}</h3><span>${x.year||''}</span></div>${context}<div class="profile-review-meta">${x.rating!=null?starIcons(x.rating,'small'):''}<span>Watched ${fmtDate(x.watched_date)}</span>${x.rewatch?'<span>↻ Rewatch</span>':''}${x.liked?'<span class="liked-text">♥ Liked</span>':''}</div><div class="profile-review-text">${reviewHtml(x.review)}</div>${reviewImagesHtml(x,{compact:true})}${tagChips(x.tags)}</div></button>`;
}
async function renderProfile(){
  const d=await api('/api/profile');cachedProfile=d.profile;setMiniProfile(d.profile);const p=d.profile;const username=p.username||'kinoala';const top=p.top5||p.top4||[];
  content.innerHTML=`<div class="profile-page"><section class="profile-header">${avatarMarkup(p.avatar_url,username,'profile-avatar')}<div class="profile-main"><div class="profile-name-row"><h1>${esc(username)}</h1><button class="secondary small" id="editProfile">Edit profile</button></div><div class="profile-meta">${p.pronoun?`<span>${esc(p.pronoun)}</span>`:''}${p.location?`<span>⌖ ${esc(p.location)}</span>`:''}</div><p>${esc(p.bio||'')}</p></div><div class="profile-stats"><div><strong>${d.stats.movies_watched||0}</strong><span>Films</span></div><div><strong>${d.stats.shows_watched||0}</strong><span>Shows</span></div><div><strong>${d.stats.episode_logs||0}</strong><span>Episodes</span></div><div><strong>${d.stats.lists||0}</strong><span>Lists</span></div></div></section>
    <section class="section profile-top5"><div class="section-head"><div><h2>Favourite Films</h2></div></div><div class="top5-row">${[0,1,2,3,4].map(i=>topFiveCard(top[i],i)).join('')}</div></section>
    <div class="profile-columns"><div class="profile-column-main">
      ${sectionRow('Recent films and Shows','',d.recent,'activity')}
      ${d.recent_reviews?.length?`<section class="section recent-reviews-section"><div class="section-head"><div><h2>Recent reviews</h2></div><button data-view="activity">More →</button></div><div class="profile-review-list">${d.recent_reviews.slice(0,4).map(recentReviewItem).join('')}</div></section>`:''}
      <section class="section"><div class="section-head"><div><h2>Lists</h2></div><button data-view="lists">View all →</button></div><div class="profile-list-row">${d.lists.slice(0,5).map(listCard).join('')||'<div class="empty">No lists yet.</div>'}</div></section>
    </div><aside class="profile-column-side">
      ${profileDiary(d.diary,d.stats.diary)}
      ${ratingsHistogram(d.ratingDistribution,d.stats.rated,{compact:true})}
      ${profileActivity(d.activities,username)}
    </aside></div></div>`;
  $('#editProfile').onclick=()=>openProfileEditor(d);$$('[data-empty-top5]').forEach(b=>b.onclick=()=>openProfileEditor(d));bindFilmCards(content);bindViewLinks(content);bindLogLinks(content);$$('[data-list-id]').forEach(el=>el.onclick=()=>showList(Number(el.dataset.listId)));
}

async function renderFilms(){
  content.innerHTML=`<div class="eyebrow">Your library</div><h1 class="page-title">Films & TV</h1><p class="page-subtitle">Everything you have added to Kinoala.</p><div class="toolbar browse-toolbar"><input id="filmFilter" type="search" placeholder="Filter your library…"><select id="mediaType"><option value="all">Films & TV</option><option value="movie">Films</option><option value="tv">TV shows</option></select><select id="filmSort"><option value="title">Title A–Z</option><option value="year">Release year</option><option value="rating">Your rating</option><option value="recent">Recently updated</option></select><label class="check-line"><input id="watchedOnly" type="checkbox"> Watched only</label><span class="spacer"></span><span id="filmCount" class="page-subtitle"></span></div><div id="filmGrid" class="film-grid"></div>`;
  const load=async()=>{const grid=$('#filmGrid');grid.innerHTML='<div class="loading-state"><div class="spinner"></div></div>';const params=new URLSearchParams({q:$('#filmFilter').value,type:$('#mediaType').value,sort:$('#filmSort').value});if($('#watchedOnly').checked)params.set('watched','1');const rows=await api(`/api/films?${params}`);$('#filmCount').textContent=`${rows.length} titles`;grid.innerHTML=rows.length?rows.map(filmCard).join(''):'<div class="empty">No titles match this filter.</div>';bindFilmCards(grid)};
  let t;$('#filmFilter').addEventListener('input',()=>{clearTimeout(t);t=setTimeout(load,170)});$('#mediaType').addEventListener('change',load);$('#filmSort').addEventListener('change',load);$('#watchedOnly').addEventListener('change',load);await load();
}
async function renderWatchlist(){const rows=await api('/api/watchlist');content.innerHTML=`<div class="eyebrow">Up next</div><div class="title-row"><div><h1 class="page-title">Watchlist</h1><p class="page-subtitle">Films and shows you want to get around to.</p></div><button class="primary" id="watchlistAdd">＋ Add title</button></div><div class="film-grid">${rows.map(filmCard).join('')||'<div class="empty">Your watchlist is empty.</div>'}</div>`;$('#watchlistAdd').onclick=focusSearch;bindFilmCards(content)}

function autoListCover(list){if(list.cover_url)return `<div class="list-cover"><img src="${esc(list.cover_url)}" alt="${esc(list.name)} cover"></div>`;const items=(list.items||[]).slice(0,4);return `<div class="list-cover cover-collage">${[0,1,2,3].map(i=>items[i]?.poster_url?`<img src="${esc(items[i].poster_url)}" alt="">`:'<span></span>').join('')}</div>`}
function listCard(list){const count=list.item_count??list.items?.length??0;return `<article class="list-card" data-list-id="${list.id}">${autoListCover(list)}<div class="list-card-copy"><h3>${esc(list.name)}</h3><p>${esc(list.description||'A personal collection.')}</p><span>${count} titles</span></div></article>`}
async function renderLists(){const lists=await api('/api/lists');content.innerHTML=`<div class="eyebrow">Collections</div><div class="title-row"><div><h1 class="page-title">Lists</h1><p class="page-subtitle">Personal collections with optional square artwork.</p></div><button class="primary" id="newList">＋ New list</button></div><div class="list-grid spotify-lists">${lists.map(listCard).join('')||'<div class="empty">Create your first list.</div>'}</div>`;$('#newList').onclick=()=>openListEditor();$$('[data-list-id]').forEach(el=>el.onclick=()=>showList(Number(el.dataset.listId)))}
async function showList(id){const lists=await api('/api/lists');const list=lists.find(l=>l.id===id);if(!list)return;content.innerHTML=`<button class="back-link" id="backLists">← All lists</button><section class="list-detail-head">${autoListCover(list)}<div><div class="eyebrow">List</div><h1>${esc(list.name)}</h1><p>${esc(list.description||'')}</p><div class="list-detail-actions"><span>${list.items.length} titles</span><button class="secondary" id="editList">Edit list</button></div></div></section><div class="film-grid">${list.items.map(filmCard).join('')||'<div class="empty">This list is empty.</div>'}</div>`;$('#backLists').onclick=renderLists;$('#editList').onclick=()=>openListEditor(list);bindFilmCards(content)}

function featuredLog(x){const bg=x.backdrop_url?`style="background-image:linear-gradient(180deg,rgba(15,19,22,.12),rgba(15,19,22,.92) 72%,#0f1316),url('${esc(x.backdrop_url)}')"`:'';return `<button class="featured-log" data-log-type="${x.log_type}" data-log-id="${x.log_id}" ${bg}><div class="featured-log-inner"><div class="featured-poster">${x.poster_url?`<img src="${esc(x.poster_url)}" alt="">`:''}</div><div class="featured-copy"><div class="eyebrow">Most recent</div><h2>${esc(x.title)}</h2><div class="featured-meta">${x.rating!=null?starIcons(x.rating,'small'):''}<span>${fmtDate(x.watched_date)}</span>${x.liked?'<span class="liked-text">♥ liked</span>':''}${x.rewatch?'<span>↻ rewatch</span>':''}</div><div class="featured-sub">${esc(logSubtitle(x))}</div>${x.review?`<div class="featured-review">${reviewHtml(x.review)}</div>`:'<p class="page-subtitle">No written review for this entry.</p>'}${tagChips(x.tags)}</div></div></button>`}
async function renderActivity(){
  const [logs,actions]=await Promise.all([api('/api/logs?limit=300'),api('/api/activity?limit=120')]);
  const latest=logs.find(x=>String(x.review||'').trim())||logs[0];const older=latest?logs.filter(x=>!(x.log_type===latest.log_type&&Number(x.log_id)===Number(latest.log_id))):[];
  content.innerHTML=`<div class="eyebrow">Your viewing history</div><div class="title-row"><div><h1 class="page-title">Activity</h1><p class="page-subtitle">Logs, reviews, rewatches, seasons and episodes in chronological order.</p></div><button class="primary" id="activityAdd">＋ Log something</button></div>${latest?featuredLog(latest):'<div class="empty">Nothing logged yet.</div>'}${older.length?`<section class="section"><div class="section-head"><div><h2>Earlier entries</h2><p>Open an entry to see its full review and previous reviews for the same title.</p></div></div><div class="compact-log-list activity-log-list">${older.map(compactLog).join('')}</div></section>`:''}${actions.length?`<details class="other-activity"><summary>Library activity</summary><div class="activity-feed">${actions.slice(0,80).map(activityRow).join('')}</div></details>`:''}`;
  $('#activityAdd').onclick=focusSearch;bindLogLinks(content);bindFilmCards(content);
}
function activityRow(a){const target=a.title?`<strong>${esc(a.title)}</strong>`:a.list_name?`<strong>${esc(a.list_name)}</strong>`:'your library';let text='updated';if(a.action==='logged')text='watched';else if(a.action==='rated')text=`rated ${a.rating!=null?starIcons(a.rating,'tiny'):''}`;else if(a.action==='liked')text='liked';else if(a.action==='watchlisted')text='added to watchlist';else if(a.action==='reviewed')text='reviewed';else if(a.action==='created_list')text='created list';else if(a.action==='added_to_list')text=`added to ${esc(a.list_name||'a list')}`;else if(a.action==='logged_season')text=`logged Season ${a.season_number}`;else if(a.action==='logged_episode')text=`logged S${String(a.season_number||0).padStart(2,'0')}E${String(a.episode_number||0).padStart(2,'0')}`;else if(a.action==='marked_watched')text='marked watched';return `<div class="activity-row" ${a.media_id?`data-film-id="${a.media_id}"`:''}><div class="activity-thumb">${a.poster_url?`<img src="${esc(a.poster_url)}" alt="">`:'<span>●</span>'}</div><div><p>${text} ${target}</p>${a.details?`<small>${esc(String(a.details).replace(/<[^>]+>/g,'').slice(0,140))}</small>`:''}</div><time>${shortDate(a.created_at)}</time></div>`}

async function openLogDetail(type,id){
  modalBackdrop.classList.remove('hidden');modal.innerHTML='<div class="loading-state"><div class="spinner"></div></div>';
  try{
    const d=await api(`/api/logs/${type}/${id}`);
    const m=await api(`/api/films/${d.entry.media_id}`);
    renderMediaModal(m,d.entry);
  }catch(e){modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button><div class="empty">${esc(e.message)}</div>`;$('#modalClose').onclick=closeModal}
}

async function renderSettings(){const s=await api('/api/settings');content.innerHTML=`<div class="eyebrow">Local setup</div><h1 class="page-title">Settings</h1><p class="page-subtitle">Kinoala remains local-first. TMDB supplies metadata and selectable artwork.</p><div class="settings-grid"><div class="settings-card"><h3>TMDB</h3><p><span class="status-dot ${s.tmdbConfigured?'ok':''}"></span>${s.tmdbConfigured?'Connected':'Not configured'}</p><div class="code">TMDB_API_READ_TOKEN=${s.tmdbConfigured?'••••••••••••••••':'YOUR_TOKEN_HERE'}</div>${s.tmdbConfigured?`<p><strong>${s.movies}</strong> films · <strong>${s.shows}</strong> TV shows · <strong>${s.unresolved}</strong> imported films still need metadata.</p><button class="primary" id="syncTmdb" ${s.unresolved===0?'disabled':''}>Sync next film batch</button><div id="syncStatus" class="page-subtitle"></div>`:''}</div><div class="settings-card"><h3>Artwork</h3><p>Each review/log can use a different TMDB poster and backdrop. The most recent entry poster is also used in the Recent section of your profile.</p></div><div class="settings-card"><h3>Database</h3><p>Your ratings, logs, reviews, lists and profile data live here:</p><div class="code">${esc(s.dbPath)}</div><p>Back up the database plus <code>public/uploads</code> for local profile/list images.</p></div><div class="settings-card"><h3>Letterboxd import</h3><p>Future exports can still be merged:</p><div class="code">npm run import -- /path/to/unzipped-export</div></div></div>`;$('#syncTmdb')?.addEventListener('click',syncTmdbBatch)}
async function syncTmdbBatch(){const btn=$('#syncTmdb'),status=$('#syncStatus');btn.disabled=true;status.textContent='Matching films with TMDB…';try{const r=await api('/api/tmdb/sync',{method:'POST',body:JSON.stringify({limit:20})});status.textContent=`Synced ${r.synced}. ${r.failed?`${r.failed} could not be matched. `:''}${r.remaining} remaining.`;toast(`TMDB sync: ${r.synced} films updated`);setTimeout(renderSettings,700)}catch(e){status.textContent=e.message;toast(e.message,'error');btn.disabled=false}}

function mediaHero(m,entry=m.latest_entry){const poster=entry?.poster_url||m.poster_url;const backdrop=entry?.backdrop_url||m.backdrop_url;const bg=backdrop?`style="background-image:linear-gradient(180deg,rgba(16,20,24,.04) 0%,rgba(16,20,24,.12) 34%,rgba(20,24,28,.62) 68%,rgba(20,24,28,.94) 86%,rgba(20,24,28,1) 100%),url('${esc(backdrop)}')"`:'';const maker=m.media_type==='tv'?(m.creators?.length?`Created by ${m.creators.map(esc).join(', ')}`:''):(m.director?`Directed by ${esc(m.director)}`:'');return `<div class="film-hero ${backdrop?'has-backdrop':''}" ${bg}><div class="detail-poster">${poster?`<img src="${esc(poster)}" alt="${esc(m.title)} poster">`:`<div class="poster-placeholder"><span>${esc(m.title)}</span></div>`}</div><div class="film-copy"><div class="eyebrow">${typeLabel(m)}</div><h2 class="cinematic-title">${esc(m.title)} <span class="year">${m.year||''}</span></h2><div class="meta-line">${maker?`<span>${maker}</span>`:''}${m.runtime?`<span>${m.runtime} min</span>`:''}${m.media_type==='tv'&&m.number_of_seasons?`<span>${m.number_of_seasons} season${m.number_of_seasons===1?'':'s'}</span>`:''}${(m.genres||[]).slice(0,3).map(g=>`<span>${esc(g)}</span>`).join('')}</div><p class="overview">${esc(m.overview||`No TMDB synopsis has been synced for this ${m.media_type==='tv'?'show':'film'} yet.`)}</p><div class="film-actions"><button class="action-icon ${m.watched?'active':''}" id="watchedToggle"><b>✓</b><span>${m.watched?'Watched':'Watch'}</span></button><button class="action-icon liked ${m.liked?'active':''}" id="likedToggle"><b>♥</b><span>${m.liked?'Liked':'Like'}</span></button><button class="action-icon ${m.in_watchlist?'active':''}" id="watchlistToggle"><b>＋</b><span>Watchlist</span></button><button class="action-icon" id="addToList"><b>☷</b><span>List</span></button></div></div></div>`}
async function openMedia(id){modalBackdrop.classList.remove('hidden');modal.innerHTML='<div class="loading-state"><div class="spinner"></div></div>';try{const m=await api(`/api/films/${id}`);renderMediaModal(m)}catch(e){modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button><div class="empty">${esc(e.message)}</div>`;$('#modalClose').onclick=closeModal}}
function mediaLatestEntry(m,x=m.latest_entry){
  if(!x)return '';
  const isLatest=Boolean(m.latest_entry&&x.log_type===m.latest_entry.log_type&&Number(x.log_id)===Number(m.latest_entry.log_id));
  const context=x.log_type==='season'?`<span class="media-entry-context">Season ${x.season_number}</span>`:x.log_type==='episode'?`<span class="media-entry-context">S${String(x.season_number||0).padStart(2,'0')}E${String(x.episode_number||0).padStart(2,'0')}</span>`:'';
  return `<section class="media-latest-entry"><div class="media-entry-head"><div><div class="eyebrow">${isLatest?'Your latest entry':'Your entry'} ${context}</div><div class="media-entry-meta">${x.rating!=null?starIcons(x.rating,'normal'):''}<span>Watched ${fmtDate(x.watched_date||x.review_date)}</span>${x.rewatch?'<span>↻ Rewatch</span>':''}${m.liked?'<span class="liked-text">♥ Liked</span>':''}</div></div><button class="secondary small" id="editMediaEntry">Edit entry / artwork</button></div>${x.review?`<div class="media-entry-review">${reviewHtml(x.review)}</div>`:'<p class="review-empty">No written review on this entry.</p>'}${reviewImagesHtml(x)}${tagChips(x.tags)}</section>`;
}
function renderMediaModal(m,entry=m.latest_entry){modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button>${mediaHero(m,entry)}<div class="modal-body">${mediaLatestEntry(m,entry)}<section class="your-rating"><div><div class="eyebrow">Your rating</div>${ratingPicker(m.rating,'overallRating')}</div>${m.rating!=null?`<strong>${ratingText(m.rating)}</strong>`:''}</section>${m.media_type==='tv'?tvBody(m):movieBody(m)}</div>`;$('#modalClose').onclick=closeModal;$('#watchedToggle').onclick=()=>toggleMediaState(m,'watched',!m.watched);$('#likedToggle').onclick=()=>toggleMediaState(m,'liked',!m.liked);$('#watchlistToggle').onclick=()=>toggleMediaState(m,'in_watchlist',!m.in_watchlist);$('#addToList').onclick=()=>openAddToList(m.id);$('#editMediaEntry')?.addEventListener('click',()=>openEditEntry(entry.log_type,entry.log_id));bindRatingPicker('overallRating',m.rating,v=>toggleMediaState(m,'rating',v,false));if(m.media_type==='tv')bindTvModal(m);else bindMovieModal(m)}
function movieBody(m){return `<section class="simple-log-cta"><div><h3>${m.diary?.length?'Diary':'Log this film'}</h3><p>${m.diary?.length?'Add another viewing or rewatch.':'Log a watch, rating, like, rewatch and review in one simple entry.'}</p></div><button class="primary" id="logMovieBtn">＋ ${m.diary?.length?'Log again':'Log or review'}</button></section>${m.diary?.length>1?`<section class="history"><div class="section-head"><div><h3>Previous entries</h3></div></div><div class="compact-log-list">${m.diary.slice(1,9).map(d=>compactLog({log_type:'movie',log_id:d.id,media_id:m.id,title:m.title,year:m.year,media_type:'movie',watched_date:d.watched_date||d.logged_date,rating:d.rating,review:d.review,rewatch:d.rewatch,tags:d.tags,liked:m.liked,poster_url:d.poster_url||m.poster_url})).join('')}</div></section>`:''}`}
function bindMovieModal(m){$('#logMovieBtn').onclick=()=>openLogSheet({mode:'movie',media:m})}
function tvBody(m){const latest=m.reviews?.find(r=>r.review);return `<section class="simple-log-cta"><div><h3>Series review</h3><p>Keep your overall series rating/review separate from season and episode logs.</p></div><button class="primary" id="reviewShowBtn">＋ Review show</button></section><section class="season-section"><div class="section-head"><div><h3>Seasons</h3><p>Open a season to log it or track individual episodes.</p></div></div><div class="season-grid">${(m.seasons||[]).map(s=>`<button class="season-card" data-season="${s.season_number}"><div class="season-poster">${s.poster_url?`<img src="${esc(s.poster_url)}" alt="">`:`<span>${esc(s.name||`Season ${s.season_number}`)}</span>`}</div><div class="season-card-copy"><strong>${esc(s.name||`Season ${s.season_number}`)}</strong><small>${s.episode_count??'—'} episodes</small><div class="progress-track"><i style="width:${s.progress||0}%"></i></div><span>${s.progress||0}% logged</span></div></button>`).join('')||'<div class="empty">No season data yet. Make sure TMDB is connected.</div>'}</div></section>${latest?`<section class="history"><h3>Latest overall review</h3><button class="review-card" data-log-type="review" data-log-id="${latest.id}"><div>${latest.rating!=null?starIcons(latest.rating,'small'):''}<time>${fmtDate(latest.watched_date||latest.review_date)}</time></div><div class="review-card-copy">${reviewHtml(latest.review)}</div></button></section>`:''}`}
function bindTvModal(m){$('#reviewShowBtn').onclick=()=>openLogSheet({mode:'review',media:m});$$('[data-season]',modal).forEach(b=>b.onclick=()=>openSeason(m.id,Number(b.dataset.season)));bindLogLinks(modal)}
async function toggleMediaState(m,key,value,reopen=true){try{await api(`/api/films/${m.id}/state`,{method:'POST',body:JSON.stringify({[key]:value})});toast(key==='rating'?(value==null?'Rating cleared':`Rated ${value} stars`):'Updated');if(reopen)await openMedia(m.id);else m[key]=value;markRefresh()}catch(e){toast(e.message,'error')}}

function artworkField(m,entry=null){
  const poster=entry?.poster_url||m.default_poster_url||m.poster_url;
  const backdrop=entry?.backdrop_url||m.default_backdrop_url||m.backdrop_url;
  const customPoster=entry?.custom_poster_path||'';
  const customBackdrop=entry?.custom_backdrop_path||'';
  const custom=Boolean(customPoster||customBackdrop);
  return `<div class="field full artwork-field" data-artwork-media="${m.id}"><label>Entry artwork <span>optional</span></label><div class="artwork-summary"><div class="artwork-poster-preview">${poster?`<img src="${esc(poster)}" alt="">`:'<span>Poster</span>'}</div><div class="artwork-backdrop-preview">${backdrop?`<img src="${esc(backdrop)}" alt="">`:'<span>Backdrop</span>'}</div><div><strong>${custom?'Custom artwork selected':'Default artwork'}</strong><p>${entry?'Change the poster or backdrop for this existing entry.':'Choose a different poster and backdrop for only this entry.'}</p><button type="button" class="secondary small" data-load-artwork>Choose artwork</button></div></div><input type="hidden" name="custom_poster_path" value="${esc(customPoster)}"><input type="hidden" name="custom_backdrop_path" value="${esc(customBackdrop)}"><div class="artwork-gallery hidden" data-artwork-gallery></div></div>`;
}
async function loadArtworkChooser(root,m){
  const gallery=$('[data-artwork-gallery]',root);if(!gallery)return;if(gallery.dataset.loaded==='1'){gallery.classList.toggle('hidden');return}gallery.classList.remove('hidden');gallery.innerHTML='<div class="loading-inline"><div class="spinner"></div>Loading TMDB artwork…</div>';
  try{const d=await api(`/api/films/${m.id}/artwork`);const selectedPoster=root.querySelector('[name="custom_poster_path"]').value;const selectedBackdrop=root.querySelector('[name="custom_backdrop_path"]').value;gallery.dataset.loaded='1';gallery.innerHTML=`<div class="artwork-group"><div class="artwork-group-head"><strong>Poster</strong><button type="button" class="ghost small" data-default-art="poster">Use default</button></div><div class="artwork-poster-grid">${d.posters.map(a=>`<button type="button" data-art-kind="poster" data-art-path="${esc(a.path||'')}" class="${a.path===selectedPoster?'selected':''}"><img src="${esc(a.thumb_url||'')}" alt=""></button>`).join('')||'<p>No alternative posters found.</p>'}</div></div><div class="artwork-group"><div class="artwork-group-head"><strong>Backdrop</strong><button type="button" class="ghost small" data-default-art="backdrop">Use default</button></div><div class="artwork-backdrop-grid">${d.backdrops.map(a=>`<button type="button" data-art-kind="backdrop" data-art-path="${esc(a.path||'')}" class="${a.path===selectedBackdrop?'selected':''}"><img src="${esc(a.thumb_url||'')}" alt=""></button>`).join('')||'<p>No alternative backdrops found.</p>'}</div></div>`;
    $$('[data-art-kind]',gallery).forEach(btn=>btn.onclick=()=>{const kind=btn.dataset.artKind;root.querySelector(`[name="custom_${kind}_path"]`).value=btn.dataset.artPath;$$(`[data-art-kind="${kind}"]`,gallery).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const img=$('img',btn);const preview=$(`.artwork-${kind}-preview`,root);preview.innerHTML=`<img src="${esc(img.src)}" alt="">`;$('.artwork-summary strong',root).textContent='Custom artwork selected'});
    $$('[data-default-art]',gallery).forEach(btn=>btn.onclick=()=>{const kind=btn.dataset.defaultArt;root.querySelector(`[name="custom_${kind}_path"]`).value='';$$(`[data-art-kind="${kind}"]`,gallery).forEach(x=>x.classList.remove('selected'));const src=kind==='poster'?(m.default_poster_url||m.poster_url):(m.default_backdrop_url||m.backdrop_url);$(`.artwork-${kind}-preview`,root).innerHTML=src?`<img src="${esc(src)}" alt="">`:`<span>${kind}</span>`;const stillCustom=root.querySelector('[name="custom_poster_path"]').value||root.querySelector('[name="custom_backdrop_path"]').value;$('.artwork-summary strong',root).textContent=stillCustom?'Custom artwork selected':'Default artwork'});
  }catch(e){gallery.innerHTML=`<div class="empty compact">${esc(e.message)}</div>`}
}
function openLogSheet({mode,media,season=null,episode=null,existing=null}){
  const isMovie=mode==='movie',isShow=mode==='review',isSeason=mode==='season',isEpisode=mode==='episode';
  const title=existing?.title||(isSeason?`${media.title} · ${season.name}`:isEpisode?`${media.title} · S${String(episode.season_number).padStart(2,'0')}E${String(episode.episode_number).padStart(2,'0')}`:media.title);
  const heading=existing?'Edit entry':isMovie?'Log film':isShow?'Review series':isSeason?'Log season':'Log episode';
  const initialRating=existing?.rating??(isMovie||isShow?media.rating:(isEpisode?episode.latest_rating:null));
  const watchedDate=existing?.watched_date||today();
  const review=existing?.review||'';const tags=existing?.tags||'';
  const liked=existing?existing.liked:media.liked;const rewatch=Boolean(existing?.rewatch);
  openSheet(`<button class="icon-btn sheet-close">×</button><div class="log-sheet-title"><div class="eyebrow">${heading}</div><h2 class="cinematic-title">${esc(title)}</h2></div><form class="sheet-form simple-review-form" id="entryLogForm"><div class="field full rating-field"><label>Rating</label>${ratingPicker(initialRating,'entryRating')}<input type="hidden" name="rating" value="${initialRating??''}"></div><div class="field"><label>Watched</label><input class="form-control" type="date" name="watched_date" value="${esc(String(watchedDate).slice(0,10))}"></div><div class="field entry-flags"><label>Entry</label><div class="flag-row"><label class="toggle-chip liked-chip"><input type="checkbox" name="liked" ${liked?'checked':''}><span>♥ Liked</span></label><label class="toggle-chip"><input type="checkbox" name="rewatch" ${rewatch?'checked':''}><span>↻ Rewatch</span></label></div></div><div class="field full review-editor-field"><label>Review</label>${reviewFormatToolbar()}<textarea class="form-control review-textarea" name="review" placeholder="Write your review…">${esc(review)}</textarea><small class="format-hint">Use headings, captions and Letterboxd-style formatting: &lt;h1&gt;, &lt;h2&gt;, &lt;h3&gt;, &lt;caption&gt;, &lt;b&gt;, &lt;i&gt; and &lt;blockquote&gt;.</small></div>${reviewImageEditor(existing)}<div class="field full"><label>Tags</label><input class="form-control" name="tags" value="${esc(tags)}" placeholder="cinema, favourite, family"></div>${artworkField(media,existing)}<div class="form-actions">${existing?'<button class="danger-button" type="button" id="deleteEntryBtn">Delete entry</button>':''}<button class="primary" type="submit">${existing?'Save changes':'Save entry'}</button></div></form>`);
  bindRatingPicker('entryRating',initialRating,v=>{$('#entryLogForm [name="rating"]').value=v??''});
  bindReviewFormatting($('#entryLogForm [name="review"]'));
  $('[data-load-artwork]',sheet).onclick=()=>loadArtworkChooser($('.artwork-field',sheet),media);
  $$('[data-review-image-path] button',sheet).forEach(btn=>btn.onclick=()=>btn.closest('[data-review-image-path]').remove());
  if(existing){
    $('#deleteEntryBtn').onclick=async()=>{
      const label=mode==='review'?'review':mode==='season'?'season log':mode==='episode'?'episode log':'diary entry';
      const confirmed=window.confirm(`Delete this ${label}?\n\nThis removes the log/review and its entry-specific artwork from Kinoala. The film or show itself stays in your library. This cannot be undone.`);
      if(!confirmed)return;
      try{
        await api(`/api/logs/${mode}/${existing.log_id}`,{method:'DELETE'});
        toast('Entry deleted');closeSheet();markRefresh();
        if(isSeason||isEpisode)await openSeason(media.id,existing.season_number||season?.season_number||episode?.season_number);
        else await openMedia(media.id);
      }catch(err){toast(err.message,'error')}
    };
  }
  const imageInput=$('#reviewImageInput');
  imageInput.addEventListener('change',()=>{
    const preview=$('#reviewImageNewPreview');preview.innerHTML='';
    const kept=$$('[data-review-image-path]',sheet).length;
    const files=[...imageInput.files];
    if(kept+files.length>8){toast('A review can contain up to 8 images','error');imageInput.value='';return}
    files.forEach(file=>{const url=URL.createObjectURL(file);preview.insertAdjacentHTML('beforeend',`<div class="review-image-edit-item new"><img src="${esc(url)}" alt="${esc(file.name)}"><span>New</span></div>`)});
  });
  $('#entryLogForm').addEventListener('submit',async e=>{
    e.preventDefault();const fd=new FormData(e.currentTarget);
    try{
      const keptPaths=$$('[data-review-image-path]',e.currentTarget).map(el=>el.dataset.reviewImagePath).filter(Boolean);
      const files=[...imageInput.files];if(keptPaths.length+files.length>8)throw new Error('A review can contain up to 8 images');
      const reviewImageData=[];for(const file of files)reviewImageData.push(await fileToDataUrl(file));
      const payload={watched_date:fd.get('watched_date'),rating:fd.get('rating'),review:fd.get('review'),tags:fd.get('tags'),rewatch:fd.get('rewatch')==='on',liked:fd.get('liked')==='on',custom_poster_path:fd.get('custom_poster_path')||null,custom_backdrop_path:fd.get('custom_backdrop_path')||null,review_image_paths:keptPaths,review_image_data:reviewImageData};
      let result;
      if(existing) result=await api(`/api/logs/${mode}/${existing.log_id}`,{method:'POST',body:JSON.stringify(payload)});
      else if(isMovie)result=await api('/api/diary',{method:'POST',body:JSON.stringify({...payload,media_id:media.id,film_id:media.id})});
      else if(isShow)result=await api(`/api/films/${media.id}/review`,{method:'POST',body:JSON.stringify(payload)});
      else if(isSeason)result=await api(`/api/tv/seasons/${season.id}/logs`,{method:'POST',body:JSON.stringify(payload)});
      else result=await api(`/api/tv/episodes/${episode.id}/logs`,{method:'POST',body:JSON.stringify(payload)});
      toast(existing?'Entry updated':'Entry saved');closeSheet();markRefresh();
      if(existing){await openLogDetail(mode,existing.log_id)}
      else if(isSeason)await openSeason(media.id,season.season_number);
      else if(isEpisode)await openSeason(media.id,episode.season_number);
      else {if(result?.id)await openLogDetail(mode,result.id);else await openMedia(media.id)}
    }catch(err){toast(err.message,'error')}
  })
}
async function openEditEntry(type,id){
  try{
    const d=await api(`/api/logs/${type}/${id}`);const media=await api(`/api/films/${d.entry.media_id}`);
    openLogSheet({mode:type,media,existing:d.entry});
  }catch(e){toast(e.message,'error')}
}

async function openSeason(showId,seasonNumber){modal.innerHTML='<div class="loading-state"><div class="spinner"></div><p>Loading season…</p></div>';try{const [show,d]=await Promise.all([api(`/api/films/${showId}`),api(`/api/tv/${showId}/seasons/${seasonNumber}`)]);renderSeason(show,d)}catch(e){modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button><div class="empty">${esc(e.message)}</div>`;$('#modalClose').onclick=closeModal}}
function renderSeason(show,d){const s=d.season;const logged=d.episodes.filter(e=>e.logged).length;modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button><button class="modal-back" id="backShow">← ${esc(show.title)}</button><div class="season-hero"><div class="detail-poster season-detail-poster">${s.poster_url?`<img src="${esc(s.poster_url)}" alt="">`:`<div class="poster-placeholder"><span>${esc(s.name||`Season ${s.season_number}`)}</span></div>`}</div><div><div class="eyebrow">${esc(show.title)}</div><h2 class="cinematic-title">${esc(s.name||`Season ${s.season_number}`)}</h2><p>${esc(s.overview||'Track this season and its individual episodes.')}</p><div class="season-progress"><strong>${logged}/${s.episode_count||d.episodes.length}</strong><span>episodes logged</span></div><button class="primary" id="logSeasonBtn">＋ Log season</button></div></div><div class="modal-body"><section class="episode-section"><div class="section-head"><div><h3>Episodes</h3><p>Each episode can have its own date, rating, review, tags and custom artwork.</p></div></div><div class="episode-list">${d.episodes.map(ep=>episodeRow(ep)).join('')||'<div class="empty">No episode metadata is cached for this season.</div>'}</div></section>${d.logs?.length?`<section class="history"><h3>Season history</h3><div class="compact-log-list">${d.logs.map(l=>compactLog({log_type:'season',log_id:l.id,media_id:show.id,title:show.title,year:show.year,media_type:'tv',season_number:s.season_number,episode_name:s.name,watched_date:l.watched_date,rating:l.rating,review:l.review,rewatch:l.rewatch,tags:l.tags,liked:show.liked,poster_url:l.poster_url||show.poster_url})).join('')}</div></section>`:''}</div>`;$('#modalClose').onclick=closeModal;$('#backShow').onclick=()=>openMedia(show.id);$('#logSeasonBtn').onclick=()=>openLogSheet({mode:'season',media:show,season:s});$$('[data-episode-id]',modal).forEach(b=>b.onclick=()=>openLogSheet({mode:'episode',media:show,season:s,episode:d.episodes.find(e=>e.id===Number(b.dataset.episodeId))}));bindLogLinks(modal)}
function episodeRow(ep){return `<div class="episode-row"><div class="episode-still">${ep.still_url?`<img src="${esc(ep.still_url)}" alt="">`:`<span>E${ep.episode_number}</span>`}</div><div class="episode-copy"><div><span class="episode-number">E${String(ep.episode_number).padStart(2,'0')}</span><strong>${esc(ep.name||`Episode ${ep.episode_number}`)}</strong></div><small>${ep.air_date?fmtDate(ep.air_date):''}${ep.runtime?` · ${ep.runtime} min`:''}</small>${ep.latest_rating!=null?starIcons(ep.latest_rating,'tiny'):''}</div><div class="episode-state">${ep.logged?`<span class="logged-badge">✓ ${ep.log_count}</span>`:''}<button class="secondary small" data-episode-id="${ep.id}">${ep.logged?'Log again':'Log'}</button></div></div>`}

async function openAddToList(mediaId){const lists=await api('/api/lists');if(!lists.length){openListEditor(null,mediaId);return}openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">Add to list</div><h2>Choose a list</h2></div><div class="choose-list">${lists.map(l=>`<button data-choose-list="${l.id}">${autoListCover(l)}<span><strong>${esc(l.name)}</strong><small>${l.items.length} titles</small></span></button>`).join('')}</div><button class="secondary full-button" id="createListInstead">＋ Create new list</button>`);$$('[data-choose-list]',sheet).forEach(b=>b.onclick=async()=>{try{await api(`/api/lists/${b.dataset.chooseList}/items`,{method:'POST',body:JSON.stringify({media_id:mediaId})});toast('Added to list');closeSheet();markRefresh()}catch(e){toast(e.message,'error')}});$('#createListInstead').onclick=()=>openListEditor(null,mediaId)}
async function fileToDataUrl(file){if(!file)return null;if(file.size>5_000_000)throw new Error('Image must be under 5 MB');return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function openListEditor(list=null,addMediaId=null){openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">${list?'Edit list':'New list'}</div><h2>${list?esc(list.name):'Create a collection'}</h2><p>Add custom square artwork, or leave it blank for a poster collage.</p></div><form class="sheet-form" id="listEditor"><div class="cover-upload-preview" id="listCoverPreview">${list?autoListCover(list):'<div class="list-cover cover-placeholder">☷</div>'}</div><div class="field full"><label>Cover image</label><input class="form-control" type="file" name="cover" accept="image/png,image/jpeg,image/webp"></div><div class="field full"><label>Name</label><input class="form-control" name="name" value="${esc(list?.name||'')}" required></div><div class="field full"><label>Description</label><textarea class="form-control" name="description">${esc(list?.description||'')}</textarea></div><div class="form-actions"><button class="primary" type="submit">${list?'Save changes':'Create list'}</button></div></form>`);const input=$('#listEditor [name="cover"]');input.onchange=()=>{const file=input.files[0];if(file){const url=URL.createObjectURL(file);$('#listCoverPreview').innerHTML=`<div class="list-cover"><img src="${url}" alt="preview"></div>`}};$('#listEditor').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const cover=await fileToDataUrl(input.files[0]);const payload={name:fd.get('name'),description:fd.get('description'),cover_data:cover};let id=list?.id;if(list)await api(`/api/lists/${list.id}`,{method:'POST',body:JSON.stringify(payload)});else{id=(await api('/api/lists',{method:'POST',body:JSON.stringify(payload)})).id}if(addMediaId)await api(`/api/lists/${id}/items`,{method:'POST',body:JSON.stringify({media_id:addMediaId})});toast(list?'List updated':'List created');closeSheet();markRefresh();if(currentView==='lists')renderLists()}catch(err){toast(err.message,'error')}})}
async function openProfileEditor(profileBundle){
  const p=profileBundle.profile;const library=await api('/api/films?watched=1&type=movie&sort=rating&limit=1000');const selected=(p.top5||p.top4||[]).map(x=>x.id);
  openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">Profile</div><h2>Edit your profile</h2></div><form class="sheet-form" id="profileEditor"><div class="profile-edit-avatar" id="avatarPreview">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc((p.username||'K')[0].toUpperCase())}</div><div class="field full"><label>Profile photo</label><input class="form-control" type="file" name="avatar" accept="image/png,image/jpeg,image/webp"></div><div class="field full"><label>Bio</label><textarea class="form-control" name="bio">${esc(p.bio||'')}</textarea></div><div class="field"><label>Location</label><input class="form-control" name="location" value="${esc(p.location||'')}"></div><div class="field"><label>Pronouns</label><input class="form-control" name="pronoun" value="${esc(p.pronoun||'')}"></div><div class="field full"><label>Top 5 films</label><div class="top5-selectors">${[0,1,2,3,4].map((_,i)=>`<select class="form-control" name="top${i}"><option value="">— Choose film —</option>${library.map(m=>`<option value="${m.id}" ${selected[i]===m.id?'selected':''}>${esc(m.title)} (${m.year||'—'})</option>`).join('')}</select>`).join('')}</div></div><div class="form-actions"><button class="primary" type="submit">Save profile</button></div></form>`);
  const avatarInput=$('#profileEditor [name="avatar"]');avatarInput.onchange=()=>{const f=avatarInput.files[0];if(f)$('#avatarPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="preview">`};
  $('#profileEditor').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const avatar=await fileToDataUrl(avatarInput.files[0]);const ids=[0,1,2,3,4].map(i=>Number(fd.get(`top${i}`))).filter(Boolean);await api('/api/profile',{method:'POST',body:JSON.stringify({bio:fd.get('bio'),location:fd.get('location'),pronoun:fd.get('pronoun'),avatar_data:avatar,top5_ids:ids})});toast('Profile updated');closeSheet();await renderProfile()}catch(err){toast(err.message,'error')}})
}


function focusSearch(){searchInput.focus();searchPanel.classList.remove('hidden');if(searchInput.value.length>=2)doSearch(searchInput.value)}
async function doSearch(query){if(query.trim().length<2){searchPanel.classList.add('hidden');return}searchPanel.classList.remove('hidden');$('#searchResults').innerHTML='<div class="loading-state search-loading"><div class="spinner"></div></div>';try{const d=await api(`/api/search?q=${encodeURIComponent(query)}`);let html='';if(d.local.length)html+=`<div class="search-group-title">In your library</div>${d.local.map(m=>searchResult(m,'local')).join('')}`;if(d.tmdb.length)html+=`<div class="search-group-title">TMDB</div>${d.tmdb.map(m=>searchResult(m,'tmdb')).join('')}`;if(!html)html='<div class="empty search-empty">No matching films or shows.</div>';$('#searchResults').innerHTML=html;$$('.search-result[data-source="local"]').forEach(el=>el.onclick=()=>{searchPanel.classList.add('hidden');openMedia(Number(el.dataset.id))});$$('.search-result[data-source="tmdb"]').forEach(el=>el.onclick=()=>isOwner?importTmdb(el.dataset.mediaType,Number(el.dataset.id)):openLoginSheet())}catch(e){$('#searchResults').innerHTML=`<div class="empty search-empty">${esc(e.message)}</div>`}}
function searchResult(m,source){const mediaType=m.media_type==='tv'?'tv':'movie';return `<div class="search-result" data-source="${source}" data-media-type="${mediaType}" data-id="${source==='local'?m.id:m.tmdb_id}">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'result-placeholder'}))">`:'<div class="result-placeholder"></div>'}<div><strong>${esc(m.title)}</strong><small>${m.year||'Unknown year'} · ${mediaType==='tv'?'TV show':'Film'}${source==='local'&&m.rating!=null?` · ${ratingText(m.rating)}★`:''}</small></div><em>${source==='local'?'Library':'TMDB'}</em></div>`}
async function importTmdb(type,tmdbId){const mediaType=type==='tv'?'tv':'movie';try{$('#searchResults').innerHTML='<div class="loading-state search-loading"><div class="spinner"></div><p>Adding title…</p></div>';const m=await api('/api/tmdb/import',{method:'POST',body:JSON.stringify({media_type:mediaType,tmdb_id:tmdbId})});if(m.media_type!==mediaType||Number(m.tmdb_id)!==Number(tmdbId))throw new Error('The selected TMDB result did not match the imported title');searchPanel.classList.add('hidden');searchInput.value='';await openMedia(m.id);markRefresh()}catch(e){toast(e.message,'error');searchPanel.classList.add('hidden')}}


function syncOwnerUi(){
  document.body.classList.toggle('is-owner',isOwner);
  const b=$('#ownerAuthBtn');if(b){b.textContent=isOwner?'Log out':'Log in';b.classList.toggle('owner-active',isOwner)}
  const settings=$('.nav [data-view="settings"]');if(settings)settings.hidden=!isOwner;
  const quick=$('#quickLogBtn');if(quick)quick.hidden=!isOwner;
}
async function refreshOwnerStatus(){try{const d=await api('/api/auth/status');isOwner=Boolean(d.authenticated)}catch{isOwner=false}syncOwnerUi()}
function openLoginSheet(){
  openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">Owner access</div><h2>Log in to Kinoala</h2><p>Browsing is public. Log in to edit your profile, logs, reviews and lists.</p></div><form class="sheet-form" id="ownerLoginForm"><div class="field full"><label>Username</label><input class="form-control" name="username" value="kinoala" autocomplete="username" required></div><div class="field full"><label>Password</label><input class="form-control" name="password" type="password" autocomplete="current-password" required></div><div class="form-actions"><button class="primary" type="submit">Log in</button></div><p class="login-error" id="ownerLoginError"></p></form>`);
  $('#ownerLoginForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),err=$('#ownerLoginError');err.textContent='';try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:fd.get('username'),password:fd.get('password')})});ownerSession=d.token;localStorage.setItem('kinoala_owner_session',ownerSession);isOwner=true;syncOwnerUi();closeSheet();toast('Editing unlocked');await navigate(currentView)}catch(ex){err.textContent=ex.message}})
}
async function ownerAuthAction(){if(!isOwner){openLoginSheet();return}try{await api('/api/auth/logout',{method:'POST'})}catch{}ownerSession='';localStorage.removeItem('kinoala_owner_session');isOwner=false;syncOwnerUi();toast('Logged out');await navigate(currentView==='settings'?'profile':currentView)}
function topFiveCard(m,index,isTv=false){
  if(!m)return isOwner?`<button class="top5-empty" data-empty-top5="${index}"><span>＋</span><b>Add ${isTv?'TV show':'film'}</b></button>`:`<div class="top5-empty preview"><span>—</span><b>Empty favourite</b></div>`;
  const bg=m.backdrop_url?`style="background-image:linear-gradient(180deg,rgba(9,13,16,.08) 0%,rgba(9,13,16,.38) 36%,rgba(12,16,19,.98) 100%),url('${esc(m.backdrop_url)}')"`:'';
  return `<article class="top5-card" data-film-id="${m.id}" ${bg}><div class="top5-content"><div class="top5-poster">${posterHtml(m)}</div><div class="top5-copy"><h3>${esc(m.title)}</h3><span>${m.year||''}</span>${m.rating!=null?starIcons(m.rating,'small'):''}</div></div></article>`;
}
function tvEntryBadge(x){const label=x.log_type==='episode'?'Episode':x.log_type==='season'?'Season':'Series';return `<span class="entry-type-badge ${x.log_type}">${label}</span>`}
function profileDiary(logs,total,{tv=false}={}){
  const rows=(logs||[]).slice(0,10);if(!rows.length)return `<section class="profile-side-block"><div class="profile-block-head"><span>DIARY</span><b>${total||0}</b></div><div class="profile-rule"></div><div class="empty compact">No diary entries yet.</div></section>`;
  const groups=[];for(const x of rows){const raw=x.watched_date||x.logged_at;if(!raw)continue;const d=new Date(`${String(raw).slice(0,10)}T12:00:00`),key=`${d.getFullYear()}-${d.getMonth()}`;let g=groups.at(-1);if(!g||g.key!==key){g={key,month:d.toLocaleString('en-AU',{month:'short'}).toUpperCase(),items:[]};groups.push(g)}g.items.push(x)}
  return `<section class="profile-side-block"><div class="profile-block-head"><span>DIARY</span><b>${total||rows.length}</b></div><div class="profile-rule"></div><div class="profile-diary">${groups.map(g=>`<div class="diary-month"><div class="diary-month-badge">${g.month}</div><div class="diary-month-items">${g.items.map(x=>`<button data-log-type="${x.log_type}" data-log-id="${x.log_id}"><time>${new Date(`${String(x.watched_date||x.logged_at).slice(0,10)}T12:00:00`).getDate()}</time><span>${esc(x.title)}${tv?tvEntryBadge(x):''}</span></button>`).join('')}</div></div>`).join('')}</div></section>`;
}
function recentReviewItem(x){
  let context='';if(x.media_type==='tv'){if(x.log_type==='season')context=`<span class="review-context">Season ${x.season_number}</span>`;else if(x.log_type==='episode')context=`<span class="review-context">S${x.season_number}E${x.episode_number} · ${esc(x.episode_name||'Episode')}</span>`;else context='<span class="review-context">Series review</span>'}
  return `<button class="profile-review-row" data-log-type="${x.log_type}" data-log-id="${x.log_id}"><div class="profile-review-poster">${x.poster_url?`<img src="${esc(x.poster_url)}" alt="">`:''}</div><div class="profile-review-copy"><div class="profile-review-title"><h3>${esc(x.title)}</h3><span>${x.year||''}</span></div>${context}<div class="profile-review-meta">${x.rating!=null?starIcons(x.rating,'small'):''}<span>Watched ${fmtDate(x.watched_date||x.logged_at)}</span>${x.rewatch?'<span>↻ Rewatch</span>':''}${x.liked?'<span class="liked-text">♥ Liked</span>':''}</div><div class="profile-review-text">${reviewHtml(x.review)}</div>${reviewImagesHtml(x,{compact:true})}${tagChips(x.tags)}</div></button>`;
}
function currentWatchingSection(rows=[]){
  if(!rows.length)return '';
  return `<section class="section current-watching-section"><div class="section-head"><div><h2>Current TV Shows being watched</h2></div></div><div class="current-watching-grid">${rows.map(m=>`<article class="watching-card" data-film-id="${m.id}"><div class="watching-top"><div class="watching-poster">${posterHtml(m)}</div><div class="watching-copy"><h3>${esc(m.title)}</h3><span>${m.watched_episodes}/${m.total_episodes} episodes · ${m.progress}%</span><div class="season-progress-list">${(m.seasons||[]).map(s=>`<div class="season-mini"><div><b>S${s.season_number}: ${s.watched}/${s.total}</b><span>${s.percent}%</span></div><div class="season-mini-track"><i style="width:${s.percent}%"></i></div></div>`).join('')}</div></div></div><div class="overall-progress"><i style="width:${m.progress}%"></i></div></article>`).join('')}</div></section>`;
}
async function renderProfile(){
  const d=await api(`/api/profile?tab=${activeProfileTab==='tv'?'tv':'films'}`),p=d.profile;cachedProfile=p;setMiniProfile(p);const username=p.username||'kinoala',top=p.top5||[],tv=activeProfileTab==='tv';
  content.innerHTML=`<div class="profile-page"><section class="profile-header">${avatarMarkup(p.avatar_url,username,'profile-avatar')}<div class="profile-main"><div class="profile-name-row"><h1>${esc(username)}</h1>${isOwner?'<button class="secondary small" id="editProfile">Edit profile</button>':'<span class="preview-badge">Public profile</span>'}</div><div class="profile-meta">${p.pronoun?`<span>${esc(p.pronoun)}</span>`:''}${p.location?`<span>⌖ ${esc(p.location)}</span>`:''}</div><p>${esc(p.bio||'')}</p></div><div class="profile-stats"><div><strong>${d.stats.movies_watched||0}</strong><span>Films</span></div><div><strong>${d.stats.shows_watched||0}</strong><span>Shows</span></div><div><strong>${d.stats.episode_logs||0}</strong><span>Episodes</span></div><div><strong>${d.stats.lists||0}</strong><span>Lists</span></div></div></section>
  <div class="profile-media-tabs"><button data-profile-tab="films" class="${tv?'':'active'}">Films</button><button data-profile-tab="tv" class="${tv?'active':''}">TV Shows</button></div>
  <section class="section profile-top5"><div class="section-head"><div><h2>${tv?'Favourite TV Shows':'Favourite Films'}</h2></div></div><div class="top5-row">${[0,1,2,3,4].map(i=>topFiveCard(top[i],i,tv)).join('')}</div></section>
  ${tv?currentWatchingSection(d.current_watching||[]):''}
  <div class="profile-columns"><div class="profile-column-main">${sectionRow(tv?'Recent TV Shows':'Recent Films','',d.recent,'activity')}${d.recent_reviews?.length?`<section class="section recent-reviews-section"><div class="section-head"><div><h2>${tv?'Recent TV Show Reviews':'Recent Reviews'}</h2></div><button data-view="activity">More →</button></div><div class="profile-review-list">${d.recent_reviews.slice(0,5).map(recentReviewItem).join('')}</div></section>`:''}<section class="section"><div class="section-head"><div><h2>Lists</h2></div><button data-view="lists">View all →</button></div><div class="profile-list-row">${d.lists.slice(0,5).map(listCard).join('')||'<div class="empty">No lists yet.</div>'}</div></section></div><aside class="profile-column-side">${profileDiary(d.diary,d.stats.diary,{tv})}${ratingsHistogram(d.ratingDistribution,d.stats.rated,{compact:true})}${profileActivity(d.activities,username)}</aside></div></div>`;
  $$('[data-profile-tab]',content).forEach(b=>b.onclick=()=>{activeProfileTab=b.dataset.profileTab;localStorage.setItem('kinoala_profile_tab',activeProfileTab);renderProfile()});$('#editProfile')?.addEventListener('click',()=>openProfileEditor(d,tv?'tv':'films'));$$('[data-empty-top5]').forEach(b=>b.onclick=()=>openProfileEditor(d,tv?'tv':'films'));bindFilmCards(content);bindViewLinks(content);bindLogLinks(content);$$('[data-list-id]').forEach(el=>el.onclick=()=>showList(Number(el.dataset.listId)));
}
async function renderWatchlist(){const rows=await api('/api/watchlist');content.innerHTML=`<div class="eyebrow">Up next</div><div class="title-row"><div><h1 class="page-title">Watchlist</h1><p class="page-subtitle">Films and shows you want to get around to.</p></div>${isOwner?'<button class="primary" id="watchlistAdd">＋ Add title</button>':''}</div><div class="film-grid">${rows.map(filmCard).join('')||'<div class="empty">Your watchlist is empty.</div>'}</div>`;$('#watchlistAdd')?.addEventListener('click',focusSearch);bindFilmCards(content)}
async function renderLists(){const lists=await api('/api/lists');content.innerHTML=`<div class="eyebrow">Collections</div><div class="title-row"><div><h1 class="page-title">Lists</h1><p class="page-subtitle">Personal collections of films and TV shows.</p></div>${isOwner?'<button class="primary" id="newList">＋ New list</button>':''}</div><div class="list-grid spotify-lists">${lists.map(listCard).join('')||'<div class="empty">No lists yet.</div>'}</div>`;$('#newList')?.addEventListener('click',()=>openListEditor());$$('[data-list-id]').forEach(el=>el.onclick=()=>showList(Number(el.dataset.listId)))}
async function showList(id){const lists=await api('/api/lists'),list=lists.find(l=>Number(l.id)===Number(id));if(!list)return;content.innerHTML=`<button class="back-link" id="backLists">← All lists</button><section class="list-detail-head">${autoListCover(list)}<div><div class="eyebrow">List</div><h1>${esc(list.name)}</h1><p>${esc(list.description||'')}</p><div class="list-detail-actions"><span>${list.items.length} titles</span>${isOwner?'<button class="secondary" id="editList">Edit list</button><button class="secondary" id="manageListItems">Add / remove titles</button>':''}</div></div></section><div class="film-grid">${list.items.map(m=>`<div class="managed-film">${filmCard(m)}${isOwner?`<button class="remove-list-item" data-remove-list-media="${m.id}" aria-label="Remove">×</button>`:''}</div>`).join('')||'<div class="empty">This list is empty.</div>'}</div>`;$('#backLists').onclick=renderLists;$('#editList')?.addEventListener('click',()=>openListEditor(list));$('#manageListItems')?.addEventListener('click',()=>openListItemsEditor(list));$$('[data-remove-list-media]').forEach(b=>b.onclick=async e=>{e.stopPropagation();try{await api(`/api/lists/${list.id}/items/${b.dataset.removeListMedia}`,{method:'DELETE'});toast('Removed from list');await showList(list.id)}catch(ex){toast(ex.message,'error')}});bindFilmCards(content)}
async function openListItemsEditor(list){
  if(!isOwner){openLoginSheet();return}const library=await api('/api/films?type=all&sort=title&limit=2000'),current=new Set((list.items||[]).map(x=>Number(x.id)));
  openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">Edit list</div><h2>${esc(list.name)}</h2><p>Add or remove any film or TV show in your Kinoala library.</p></div><div class="field full"><label>Search library</label><input class="form-control" id="listItemSearch" placeholder="Search films and TV shows…"></div><div class="list-item-manager" id="listItemManager"></div>`);
  const render=(q='')=>{q=q.trim().toLowerCase();const rows=library.filter(m=>!q||m.title.toLowerCase().includes(q)).slice(0,160);$('#listItemManager').innerHTML=rows.map(m=>`<div class="list-manage-row"><div class="list-manage-poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="">`:''}</div><div><strong>${esc(m.title)}</strong><small>${m.year||'—'} · ${m.media_type==='tv'?'TV show':'Film'}</small></div><button class="${current.has(Number(m.id))?'danger-button':'secondary'} small" data-toggle-list-media="${m.id}">${current.has(Number(m.id))?'Remove':'Add'}</button></div>`).join('')||'<div class="empty compact">No matching titles.</div>';$$('[data-toggle-list-media]',sheet).forEach(btn=>btn.onclick=async()=>{const mid=Number(btn.dataset.toggleListMedia);try{if(current.has(mid)){await api(`/api/lists/${list.id}/items/${mid}`,{method:'DELETE'});current.delete(mid)}else{await api(`/api/lists/${list.id}/items`,{method:'POST',body:JSON.stringify({media_id:mid})});current.add(mid)}render($('#listItemSearch').value);markRefresh()}catch(ex){toast(ex.message,'error')}})};$('#listItemSearch').addEventListener('input',e=>render(e.target.value));render();
}
function openListEditor(list=null,addMediaId=null){
  if(!isOwner){openLoginSheet();return}openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">${list?'Edit list':'New list'}</div><h2>${list?esc(list.name):'Create a collection'}</h2><p>Add custom square artwork, then manage films and TV shows inside the list.</p></div><form class="sheet-form" id="listEditor"><div class="cover-upload-preview" id="listCoverPreview">${list?autoListCover(list):'<div class="list-cover cover-placeholder">☷</div>'}</div><div class="field full"><label>Cover image</label><input class="form-control" type="file" name="cover" accept="image/png,image/jpeg,image/webp"></div><div class="field full"><label>Name</label><input class="form-control" name="name" value="${esc(list?.name||'')}" required></div><div class="field full"><label>Description</label><textarea class="form-control" name="description">${esc(list?.description||'')}</textarea></div><div class="form-actions"><button class="primary" type="submit">${list?'Save changes':'Create list'}</button></div></form>`);const input=$('#listEditor [name="cover"]');input.onchange=()=>{const file=input.files[0];if(file)$('#listCoverPreview').innerHTML=`<div class="list-cover"><img src="${URL.createObjectURL(file)}" alt="preview"></div>`};$('#listEditor').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const cover=await fileToDataUrl(input.files[0]),payload={name:fd.get('name'),description:fd.get('description'),cover_data:cover};let id=list?.id;if(list)await api(`/api/lists/${list.id}`,{method:'POST',body:JSON.stringify(payload)});else{id=(await api('/api/lists',{method:'POST',body:JSON.stringify(payload)})).id}if(addMediaId)await api(`/api/lists/${id}/items`,{method:'POST',body:JSON.stringify({media_id:addMediaId})});toast(list?'List updated':'List created');closeSheet();markRefresh();if(currentView==='lists')await showList(id)}catch(err){toast(err.message,'error')}})
}
async function openProfileEditor(profileBundle,tab=activeProfileTab){
  if(!isOwner){openLoginSheet();return}const p=profileBundle.profile,tv=tab==='tv',library=await api(`/api/films?type=${tv?'tv':'movie'}&sort=rating&limit=2000`),selected=(p.top5||[]).map(x=>Number(x.id));
  openSheet(`<button class="icon-btn sheet-close">×</button><div class="sheet-head"><div class="eyebrow">Profile</div><h2>Edit ${tv?'TV':'film'} profile</h2></div><form class="sheet-form" id="profileEditor"><div class="profile-edit-avatar" id="avatarPreview">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc((p.username||'K')[0].toUpperCase())}</div><div class="field full"><label>Profile photo</label><input class="form-control" type="file" name="avatar" accept="image/png,image/jpeg,image/webp"></div><div class="field full"><label>Bio</label><textarea class="form-control" name="bio">${esc(p.bio||'')}</textarea></div><div class="field"><label>Location</label><input class="form-control" name="location" value="${esc(p.location||'')}"></div><div class="field"><label>Pronouns</label><input class="form-control" name="pronoun" value="${esc(p.pronoun||'')}"></div><div class="field full"><label>Top 5 ${tv?'TV shows':'films'}</label><div class="top5-selectors">${[0,1,2,3,4].map((_,i)=>`<select class="form-control" name="top${i}"><option value="">— Choose ${tv?'show':'film'} —</option>${library.map(m=>`<option value="${m.id}" ${selected[i]===Number(m.id)?'selected':''}>${esc(m.title)} (${m.year||'—'})</option>`).join('')}</select>`).join('')}</div></div><div class="form-actions"><button class="primary" type="submit">Save profile</button></div></form>`);const avatarInput=$('#profileEditor [name="avatar"]');avatarInput.onchange=()=>{const f=avatarInput.files[0];if(f)$('#avatarPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="preview">`};$('#profileEditor').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const avatar=await fileToDataUrl(avatarInput.files[0]),ids=[0,1,2,3,4].map(i=>Number(fd.get(`top${i}`))).filter(Boolean),payload={bio:fd.get('bio'),location:fd.get('location'),pronoun:fd.get('pronoun'),avatar_data:avatar,[tv?'top5_tv_ids':'top5_film_ids']:ids};await api('/api/profile',{method:'POST',body:JSON.stringify(payload)});toast('Profile updated');closeSheet();await renderProfile()}catch(err){toast(err.message,'error')}})
}
async function openLogDetail(type,id){modalBackdrop.classList.remove('hidden');modal.innerHTML='<div class="loading-state"><div class="spinner"></div></div>';try{const entry=await api(`/api/logs/${type}/${id}`),m=await api(`/api/films/${entry.media_id}`);renderMediaModal(m,entry)}catch(e){modal.innerHTML=`<button class="icon-btn modal-close" id="modalClose">×</button><div class="empty">${esc(e.message)}</div>`;$('#modalClose').onclick=closeModal}}
async function openEditEntry(type,id){if(!isOwner){openLoginSheet();return}try{const entry=await api(`/api/logs/${type}/${id}`),media=await api(`/api/films/${entry.media_id}`);openLogSheet({mode:type,media,existing:entry})}catch(e){toast(e.message,'error')}}
async function renderSettings(){
  if(!isOwner){content.innerHTML='<div class="empty"><h3>Owner only</h3><p>Log in to edit Kinoala settings.</p></div>';return}const s=await api('/api/settings');
  content.innerHTML=`<div class="eyebrow">Cloud setup</div><h1 class="page-title">Settings</h1><p class="page-subtitle">Kinoala is running on GitHub Pages with Supabase handling data, authentication and uploads.</p><div class="settings-grid"><div class="settings-card"><h3>TMDB</h3><p><span class="status-dot ${s.tmdb_configured?'ok':''}"></span>${s.tmdb_configured?'Connected':'Not configured'}</p>${!s.tmdb_configured?`<form id="tmdbTokenForm"><label>TMDB Read Access Token</label><input class="form-control" type="password" name="token" placeholder="Paste token"><button class="primary" type="submit">Connect TMDB</button></form>`:`<p><strong>${s.unresolved_movies||0}</strong> imported films still need TMDB metadata.</p><button class="primary" id="syncTmdb" ${s.unresolved_movies===0?'disabled':''}>Sync next film batch</button><div id="syncStatus" class="page-subtitle"></div>`}</div><div class="settings-card"><h3>Cloud database</h3><p>Ratings, reviews, logs, lists, profile data and TV progress are stored in Supabase.</p><div class="code">Supabase · ${s.total_media||0} titles</div></div><div class="settings-card"><h3>Public preview</h3><p>Visitors can browse Kinoala without editing. Your owner login unlocks profile editing, logging, lists and artwork.</p></div></div>`;$('#syncTmdb')?.addEventListener('click',syncTmdbBatch);$('#tmdbTokenForm')?.addEventListener('submit',async e=>{e.preventDefault();const token=new FormData(e.currentTarget).get('token');try{await api('/api/settings/tmdb',{method:'POST',body:JSON.stringify({token})});toast('TMDB connected');renderSettings()}catch(ex){toast(ex.message,'error')}})
}
async function syncTmdbBatch(){const btn=$('#syncTmdb'),status=$('#syncStatus');if(btn)btn.disabled=true;if(status)status.textContent='Matching films with TMDB…';try{const r=await api('/api/tmdb/sync',{method:'POST',body:JSON.stringify({limit:20})});if(status)status.textContent=`Synced ${r.synced}. ${r.failed?`${r.failed} could not be matched. `:''}${r.remaining} remaining.`;toast(`TMDB sync: ${r.synced} films updated`);setTimeout(renderSettings,700)}catch(e){if(status)status.textContent=e.message;toast(e.message,'error');if(btn)btn.disabled=false}}

$$('.nav [data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$$('.brand,.mobile-logo').forEach(b=>b.addEventListener('click',()=>navigate('profile')));
$('#miniProfile')?.addEventListener('click',()=>navigate('profile'));
$('#quickLogBtn').addEventListener('click',focusSearch);
$('#closeSearch').addEventListener('click',()=>searchPanel.classList.add('hidden'));
searchInput.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>doSearch(searchInput.value),220)});
searchInput.addEventListener('focus',()=>{if(searchInput.value.length>=2)doSearch(searchInput.value)});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();focusSearch()}if(e.key==='Escape'){searchPanel.classList.add('hidden');if(!sheetBackdrop.classList.contains('hidden'))closeSheet();else if(!modalBackdrop.classList.contains('hidden'))closeModal()}});
modalBackdrop.addEventListener('click',e=>{if(e.target===modalBackdrop)closeModal()});
sheetBackdrop.addEventListener('click',e=>{if(e.target===sheetBackdrop)closeSheet()});

(async function bootKinoalaCloud(){
  await refreshOwnerStatus();
  $('#ownerAuthBtn')?.addEventListener('click',ownerAuthAction);
  syncOwnerUi();
  await navigate('profile');
})();
